uffd: fixed for exiting exiting program as user
checkpoint-restore/criu pull request #1483
Opened 2021-05-21 09:27 UTC by nithin-jaikar

While Dumping the process, it fails and exits as a user because of kerndat_uffd() returns -1 and due permission error 
uffd = syscall(SYS_userfaultfd, flags); this function fails inturn kerndat_uffd() fails. 
In the change it ignores the permission error and proceeds further.

2021-05-21 09:34 UTC, xemul commented on criu/kerndat.c
> +	pr_msg("open fd: %d, %s  \n",fd,strerror(errno));
This pr_msg() doesn't belong to this patch.

2021-05-21 09:37 UTC, xemul requested changes
@nithin-jaikar rework the PR, leave only the EPERM checking of uffd opening and write a proper patch comment.

2021-05-21 09:37 UTC, xemul commented on criu/kerndat.c
> +	pr_msg("open acess: %d, %s  \n",ret,strerror(errno));
Please, drop this change. Missing permissions are found out by EACCESS errno of open.

2021-05-21 09:54 UTC, Snorch commented on criu/uffd.c
> +		}
I worry that this patch introduces a bug. E.g. If we got EPERM errno from uffd_open() and return 0 from uffd_open() to setup_uffd(). Next send_uffd would send random fd at index "0" into lazy pages socket, which is probably unexpected.

2021-05-21 11:46 UTC, xemul commented
@nithin-jaikar , don't add 5th commit, please. Remove all commits and leave only one.

2021-05-21 13:59 UTC, xemul requested changes
The patch (not PR, but the very commit) must have a descriptive comment

2021-05-21 13:59 UTC, xemul commented on criu/kerndat.c
> -
Remove this hunk

2021-05-21 13:59 UTC, xemul commented on criu/kerndat.c
> +		pr_err("Uffd loader is not loaded \n");
Indentation is broken

2021-05-21 15:27 UTC, xemul commented
@nithin-jaikar , you've somehow pulled in the Adrian's patch, then merged yours with his and then added the fix I requested as another commit. Please, be more attentive and make a proper PR.

2021-05-21 15:53 UTC, xemul commented
Ok, @nithin-jaikar , now let's add the comment to the commit (the text that accompanies the pull-request can be just copied)

2021-05-21 15:55 UTC, xemul requested changes

2021-05-21 15:55 UTC, xemul commented on criu/kerndat.c
> +			pr_info("uffd loader is not loaded. \n");
The logging text  should be "Lazy pages are disabled\n"

2021-05-21 16:38 UTC, adrianreber commented
From the PR description it is not clear to me what this tries to solve. Some more details how this could happen would be interesting.

2021-05-21 16:41 UTC, xemul commented
@adrianreber , this is the part of "dump shared memory as user" task.

The "criu dump" used to work from non-root some time ago, but then this mode testing stopped and the functionality got broken. On of the found problems is that non-root is not allowed to open uffd, so criu cannot even check the kerndat stuff.

2021-05-21 16:45 UTC, adrianreber commented
Ah, thanks. I saw similar errors when doing the non-root changes in #1155 

Anyway, that information would be good to have in the commit and/or PR.

2021-05-21 18:13 UTC, xemul commented
Whee, comment commit message is mastered!
@nithin-jaikar , now please read https://criu.org/How_to_submit_patches and make the commit message look the way it must. E.g. like this

````
kerndat: Handle non-root mode when checking uffd

When criu is run as user it fails and exits because of kerndat_uffd() returning -1.
This, in turn, happens after uffd = syscall(SYS_userfaultfd, flags); which only works
for root.

In the change it ignores the permission error and proceeds further just like it's done
for e.g. pagemap checking.

Signed-off-by: Nithin Jaikar J <jaikar006@gmail.com>
````

2021-05-21 18:24 UTC, xemul approved these changes

2021-05-21 19:03 UTC, rst0git approved these changes
LGTM

2021-05-24 07:11 UTC, Snorch requested changes
`#define EPERM            1`

Should not we differentiate errno == EPERM from syscall SYS_userfaultfd and later errors in uffd_open()

2021-05-30 03:09 UTC, merged

2021-05-31 08:10 UTC, Snorch commented
I still think that my objection is valid, so https://github.com/checkpoint-restore/criu/pull/1493