s390x: fix building with latest Linux kernel
checkpoint-restore/criu pull request #2232
Opened 2023-07-31 17:19 UTC by adrianreber

Building on the latest Linux kernel (6.5-rc1) fails with:
```
In file included from compel/include/uapi/compel/asm/infect-types.h:7,
                 from compel/arch/s390/src/lib/infect.c:12:
compel/arch/s390/src/lib/infect.c: In function 'rewind_psw': compel/arch/s390/src/lib/infect.c:157:29: error: 'UL' undeclared (first use in this function)
  157 |         mask = (psw->mask & PSW_MASK_EA) ? -1UL : (psw->mask & PSW_MASK_BA) ? (1UL << 31) - 1 : (1UL << 24) - 1;
      |                             ^~~~~~~~~~~
compel/arch/s390/src/lib/infect.c:157:29: note: each undeclared identifier is reported only once for each function it appears in
compel/arch/s390/src/lib/infect.c: In function 'get_ri_cb':
compel/arch/s390/src/lib/infect.c:272:25: error: 'UL' undeclared (first use in this function)
  272 |         if (psw->mask & PSW_MASK_RI)
      |                         ^~~~~~~~~~~
compel/arch/s390/src/lib/infect.c: In function 's390_disable_ri_bit':
compel/arch/s390/src/lib/infect.c:289:23: error: 'UL' undeclared (first use in this function)
  289 |         psw->mask &= ~PSW_MASK_RI;
      |                       ^~~~~~~~~~~
compel/arch/s390/src/lib/infect.c: In function 'arch_can_dump_task':
compel/arch/s390/src/lib/infect.c:523:25: error: 'UL' undeclared (first use in this function)
  523 |         if (psw->mask & PSW_MASK_RI) {
      |
```
This is caused by:

https://github.com/torvalds/linux/commit/b8af5999779d1225c82fcc960223625b279f5f0d

This is fixed with this patch.

2023-07-31 17:27 UTC, yselkowitz requested changes
While IMO it would be best to add the missing `#include <linux/const.h>` to the s390 asm/ptrace.h in the kernel headers themselves, these includes should probably be where `#include <asm/ptrace.h>` is stated.

2023-07-31 17:27 UTC, yselkowitz commented on compel/arch/s390/src/lib/infect.c
> +#include <linux/const.h>
Shouldn't this be in compel/arch/s390/src/lib/include/uapi/asm/infect-types.h which contains the `#include <asm/ptrace.h>`?

2023-07-31 17:27 UTC, yselkowitz commented on criu/arch/s390/crtools.c
> +#include <linux/const.h>
Wouldn't criu/arch/s390/include/asm/restorer.h which contains the `#include <asm/ptrace.h>` be a better place for this?

2023-07-31 17:37 UTC, adrianreber commented
I also reached out to the original authors of that kernel change.

2023-07-31 18:49 UTC, adrianreber commented
https://lore.kernel.org/all/20230731183926.330932-1-hca@linux.ibm.com/

2023-08-01 14:45 UTC, adrianreber commented
It seems the kernel fix will make it into rc5. No need to fix it in CRIU then I think.

2023-08-09 13:47 UTC, yselkowitz commented
If the fix has landed in a 6.5 RC then I think this can be closed.

2023-09-10 20:42 UTC, closed without merging

2023-09-10 20:42 UTC, adrianreber commented
Closed as it was fixed in the kernel.